### ISSUE TITLE
JOSS reviewer comments, submission 4655

### ISSUE THREAD

**Issue by simonpcouch** [adriancorrendo/metrica#28]
Hey there!

This is part of my review for your submission to JOSS at openjournals/joss-reviews#4655.

I really enjoyed checking out this package! The package is principled and very well documented. Particularly well-scoped—I appreciate that you defer to existing data structures for function output, e.g. lists and data frames, and existing tools for existing operations in vignettes, e.g. `purrr::group_map` for applications to list-columns.

A few comments:

> **Data sharing:** If the paper contains original data, data are accessible to the reviewers. If the paper contains no original data, please check this item.

For the most part, this is true, though the data included [in some vignettes](https://adriancorrendo.github.io/metrica/articles/apsim_open.html) under the `testthat` directory is not immediately available for users of the software:

``` r
soybean.out <- metrica::import_apsim_out(filepath = "../tests/testthat/examples/soybean.out")

#... 

soybean.db <- metrica::import_apsim_db(filename = "soybean.example.db", folder = "../tests/testthat/examples/")
```

I was able to read these in by pulling the source locally and adjusting the filepaths. These either ought to be included as data with the package, saved to file in the vignette, and then read in with the `metrica::import_*` functions, or simply read in as files from a GitHub `raw` URL. The `file.path()` function can be used to create OS-independent filepaths.

> **Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

You write in your paper "the first step is to install R (>= 4.2.0)," though your listed needed R version in DESCRIPTION is 2.1.0. These ought to be consistent, if included in the paper.

> **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I haven't been able to track down a CONTRIBUTING file, code of conduct, README section on contributing, or GitHub issue/PR template. I would feel confident checking off this box with any one of these present!

> **Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

The help-files are really well-written. Many of the them refer to [these vignettes](https://adriancorrendo.github.io/metrica/articles/available_metrics_classification.html) giving formulas and higher-level descriptions, though many of the terms in the formulas are not documented. `B^2`, for instance, is ambiguous in context, and the `TP`/`TN`/`FP`/etc notations are not self-explanatory.

-------

As for the paper,

> **State of the field:** Do the authors describe how this software compares to other commonly-used packages?

Your bullet points beginning at line 60 are generally informative for describing the unique advantages of your package.

In the paper, you write:

> -   the most extensive collection of prediction performance metrics for regression and classification models up to date.

At first glance, this doesn't seem to be true given the packages you've cited. Loosely:

``` r
library(cvms)
length(formalArgs(gaussian_metrics)) +
length(formalArgs(binomial_metrics)) +
length(formalArgs(multinomial_metrics))
#> [1] 84
```

or

https://github.com/tidymodels/yardstick/blob/main/NAMESPACE#L3-L182

Metric calculation modules/libraries from non-R ecosystems, as well, can be [quite extensive](https://scikit-learn.org/stable/modules/model_evaluation.html).

...which is okay! I'd just recommend removing that line from the paper, or clarifying it with some qualifiers.

> **Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?

The paper is generally well-written!

The "Package features" section is quite long, and includes elements that I haven't seen in other accepted JOSS papers. I'd recommend cutting the "Package features" section from "System requirements and installation" on, currently lines 86 through 109.

I came across a few grammatical errors while reviewing, and would like to see another round of copy edits before recommending acceptance. Would be glad to put in a PR with copy edits, if appreciated!

> **References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax](https://pandoc.org/MANUAL.html#extension-citations)?

Many software names in these entries are not case protected, resulting in the first letters to be capitalized / made lowercase when they ought not to be. e.g. "Cvms: ..." ought to read `{cvms}:`... in the LaTeX.

**Comment by adriancorrendo** [comment]
Dear reviewers,

Thank you very much for your revisions that help us to improve this project!

Changes have been made to both branches of the repository (master and JOSS)

Please, you may find next the point-by-point response (one answer per comment):

> **1. Data sharing**: If the paper contains original data, data are accessible to the reviewers. If the paper contains no original data, please check this item.
For the most part, this is true, though the data included [in some vignettes](https://adriancorrendo.github.io/metrica/articles/apsim_open.html) under the testthat directory is not immediately available for users of the software:
`soybean.out <- metrica::import_apsim_out(filepath = "../tests/testthat/examples/soybean.out")`
#... 
`soybean.db <- metrica::import_apsim_db(filename = "soybean.example.db", folder = "../tests/testthat`/examples/")
I was able to read these in by pulling the source locally and adjusting the filepaths. These either ought to be included as data with the package, saved to file in the vignette, and then read in with the metrica::import_* functions, or simply read in as files from a GitHub raw URL. The file.path() function can be used to create OS-independent filepaths.

**Answer**
Thank you very much for this comment. Following the request, we have included the files with the package as part of “inst/extdata” so they are now more ready available for users. However, please note that both files have the peculiarity of not being “complete datasets” (because they only bring "predictions"). The idea of these functions is to simply import the “predictions” of the APSIM files to the R environment. Yet, users must match these imported predictions with their corresponding “observed” values (using dplyr::left_join() ) but this widely vary from one case to another, so it’s a separate step for users. Thus, any of these files can be used directly as an input to any other of the package functions to estimate prediction “performance”. They can only be input of the “import_*” functions. 

- Solution 
At the corresponding [vignette](https://adriancorrendo.github.io/metrica/articles/apsim_open.html), we show users how to get access to their local copy of the files, now as part of the "extdata" folder within the package directory. These lines work  in a OS-independent way.

-- For APSIM Classic (*.out)
`apsim_out_filepath <- [system.file](https://rdrr.io/r/base/system.file.html)("extdata/soybean.out", package = "metrica")`
`soybean.out <- metrica::[import_apsim_out](https://adriancorrendo.github.io/metrica/reference/import_apsim_out.html)(filepath = apsim_out_filepath)`

-- For APSIM NextGeneration (*.db)
`apsim_db_folderpath <- [system.file](https://rdrr.io/r/base/system.file.html)("extdata", package = "metrica")`
`soybean.db <- metrica::[import_apsim_db](https://adriancorrendo.github.io/metrica/reference/import_apsim_db.html)(filename = "soybean.example.db", folder = apsim_db_folderpath)`

**Comment by adriancorrendo** [comment]
> **2. Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.
You write in your paper "the first step is to install R (>= 4.2.0)," though your listed needed R version in DESCRIPTION is 2.1.0. These ought to be consistent, if included in the paper.

- **Answer**
Thank you for the catch! After double-checking, the correct minimum version required based on dependencies is R >= 3.6.2.
However, following comment No. 6 recommending to reduce the corresponding section, we have simply removed this line from the article. After all, being an R-package already implies that R is required.

**Comment by adriancorrendo** [comment]
> **3. Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
I haven't been able to track down a CONTRIBUTING file, code of conduct, README section on contributing, or GitHub issue/PR template. I would feel confident checking off this box with any one of these present!

- **Answer**:
Thank you very much for this suggestion. As suggested, we have included:
  - [Contributing to our package](https://adriancorrendo.github.io/metrica/index.html#5-contributing-to-our-package) and [Code of conduct](https://adriancorrendo.github.io/metrica/index.html#6-code-of-conduct) sections into the README file.
   - A [CODE_OF_CONDUCT article](https://adriancorrendo.github.io/metrica/CODE_OF_CONDUCT.html) accompanying the documentation.

**Comment by adriancorrendo** [comment]
> **4. Functionality documentation:** Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?
The help-files are really well-written. Many of the them refer to [these vignettes](https://adriancorrendo.github.io/metrica/articles/available_metrics_classification.html) giving formulas and higher-level descriptions, though many of the terms in the formulas are not documented. B^2, for instance, is ambiguous in context, and the TP/TN/FP/etc notations are not self-explanatory.

- **Answer**:
Thank you for this comment! In line with the suggestion, we have modified the [corresponding vignette](https://adriancorrendo.github.io/metrica/articles/available_metrics_classification.html#list-of-classification-metrics-categorical-variables) providing a list of abbreviations by the end of the table as follows: 

**List of abbreviations:**
P = positive (true + false)
N = negative (true + false)
TP = true positive
TN = true negative
FP = false positive
FN = false negative
TPR = true positive rate
TNR = true negative rate
FPR = false positive rate
FNR = false negative rate
PPV = positive predictive value
B = coefficient B (a.k.a. beta) indicating the weight to be applied to the estimation of `fscore` (as $B^2$).

**Comment by adriancorrendo** [comment]
> **5. State of the field**: Do the authors describe how this software compares to other commonly-used packages?
Your bullet points beginning at line 60 are generally informative for describing the unique advantages of your package.
In the paper, you write:
•	the most extensive collection of prediction performance metrics for regression and classification models up to date.
At first glance, this doesn't seem to be true given the packages you've cited. Loosely:
library(cvms)
length(formalArgs(gaussian_metrics)) +
length(formalArgs(binomial_metrics)) +
length(formalArgs(multinomial_metrics))
#> [1] 84
or
https://github.com/tidymodels/yardstick/blob/main/NAMESPACE#L3-L182
Metric calculation modules/libraries from non-R ecosystems, as well, can be [quite extensive](https://scikit-learn.org/stable/modules/model_evaluation.html).
...which is okay! I'd just recommend removing that line from the paper, or clarifying it with some qualifiers.

- **Answer**:
Thank you for the comments here. In line with the recommendation, and since the number of metrics of packages may evolve over time, we have softened the tone of the statement to the following at Line 60:
“- one of the most extensive collections of prediction performance metrics for regression and classification models in R.”

Please, note that we have also added that this is specifically “in R”.

Regarding the meaning of “the most extensive collection of metrics”, we would like to expand what we tried to mean. Simply, we just wanted to refer to the number of error of goodness of fit “metrics” like RMSE, MAE, etc. The counts you have provided above for cvms and yardstick is counting for “arguments” but not necessarily error “metrics”. Moreover, there are numerous classification metrics of the 84 count from cvms that are counted twice (or more) between binomial_metrics() and multinomial_metrics().

**For regression**:
1. In the case of **metrica**, the total of available regression metrics is 50:
https://adriancorrendo.github.io/metrica/articles/available_metrics_regression.html

2. **cvms** gaussian_metrics (regression) comes to a total of 20, detailed on https://cran.r-project.org/web/packages/cvms/vignettes/available_metrics.html, and given the list from gaussian_metrics():
`c(rmse,  mae ,  nrmse_rng ,  nrmse_iqr ,  nrmse_std ,  nrmse_avg ,  rae ,  rse ,  rrse ,  rmsle , male,  mape ,  mse ,  tae ,  tse ,  r2m ,  r2c ,  aic ,  aicc ,  bic)`

3. In the case of **yardstick**, detailed on https://yardstick.tidymodels.org/articles/metric-types.html, the total of regression metrics (specified as “numeric” type) are 16 given:
`c(ccc, huber_loss, huber_loss_pseudo, iic, mae, mape, mase, mpe, msd, poisson_log_loss, rmse, rpd, rpiq, rsq, rsq_trad, smape)`

**For classification**:
1. In **metrica**, the available classification metrics are a total of 26:
https://adriancorrendo.github.io/metrica/articles/available_metrics_classification.html
2. **yardstick** offers a total of 23 classification metrics as detailed here: https://yardstick.tidymodels.org/articles/metric-types.html#metrics
3. **cvms** brings a total 17 classification metrics, https://cran.r-project.org/web/packages/cvms/vignettes/available_metrics.html, which are duplicated between binomial & multinomial, but the latter bring the option to get overall, macro (one vs all), or weighted-type estimations.

Functions in **metrica**, automatically detect the number of classes to run either binomial or multinomial. Then the option of obtaining overall vs per-class metrics estimates is managed with the “atom” argument, so there is no need to repeat the function. My understanding is that **yardstick** functions do almost the same. Thus, **cvms** seems to offer a larger number of classification metrics, but actually, it’s just a repetition of the same metrics but changing the way of estimation.

**Comment by adriancorrendo** [comment]
> ** 6. Quality of writing:** Is the paper well written (i.e., it does not require editing for structure, language, or writing quality)?
The paper is generally well-written!
The "Package features" section is quite long, and includes elements that I haven't seen in other accepted JOSS papers. I'd recommend cutting the "Package features" section from "System requirements and installation" on, currently lines 86 through 109.
I came across a few grammatical errors while reviewing, and would like to see another round of copy edits before recommending acceptance. Would be glad to put in a PR with copy edits, if appreciated!

- **Answer**:
We deeply appreciate the suggestions and the offer to check for grammatical expressions. As recommended, we have substantially reduced the “Package features” section by removing the “Software Requirements and installation”, and the code to generate the examples **No. 1** and **No. 2**. 

Nonetheless, if the reviewers agree, we would like to keep two parts of this section: 
i) “Using the functions” (shortened), which provides relevant details about the basic inputs and defaults for regression, binomial and multinomial cases, and 
ii) The “Examples No.1 and No. 2” which show two of the main visual outputs that can be obtained with specific package functions (but removing the code).

Regarding the offer to add copy edits, please, we would be more than glad to count with those through a PR. Thank you!

**Comment by adriancorrendo** [comment]
> ** 7. References:** Is the list of references complete, and is everything cited appropriately that should be cited (e.g., papers, datasets, software)? Do references in the text use the proper [citation syntax](https://pandoc.org/MANUAL.html#extension-citations)?
Many software names in these entries are not case protected, resulting in the first letters to be capitalized / made lowercase when they ought not to be. e.g. "Cvms: ..." ought to read {cvms}:... in the LaTeX.

- **Answer**:
Thank you very much for this comment. In line with the suggestion, we have modified the citation syntax in order make the name of the packages “case protected”. We have also fixed other minor typos within the references.bib file.

**Comment by adriancorrendo** [comment]
On behalf of all the collaborator of the **metrica** project, I would like to express gratitude for your time and patience revising our package.

Please, just let us know if any additional revisions are required.

Best regards,

ADRIAN

**Comment by simonpcouch** [comment]
@adriancorrendo, your edits look great, and I very much appreciate the detailed responses in this thread! I'll close this issue and sign off on the remaining checkboxes in the review issue.

Yall have put together a wonderful package, and I'm glad to have had the chance to check it out.🙂
