### ISSUE TITLE
Correction required in Metrica regarding Duveiller’s Lambda Coefficient

### ISSUE THREAD

**Issue by Amit1979-UniBonn** [adriancorrendo/metrica#34]
Dear Adrian, 
I came across one correction regarding "lambda" Duveiller’s Lambda Coefficient that you have in Metrica
Gregory Duveiller, published the corrected version of the equation.
could you please update the equation in Metrica?
[s41598-022-23771-z.pdf](https://github.com/adriancorrendo/metrica/files/10732931/s41598-022-23771-z.pdf)

Thanks in advance,

**Comment by adriancorrendo** [comment]
Thanks, Amit.

This change actually won't affect the estimation when using the function "lambda()".
The main reason is that it only involves the term of "k", which for the predicted:observed case is assumed to be 0 (because k = 0 when coefficient of correlation is r >= 0). So the current lambda function assumes that k = 0.
It is very unlikely that r < 0 (negative correlation) for pred vs obs values, since that would mean that model predictions are extremely wrong, and model should be discarded.

Anyway, I will modify the corresponding section of the documentation.

Hope this brief explanation helps.

Best regards,

ADRIAN

**Comment by Amit1979-UniBonn** [comment]
Thanks Adrian.

**Comment by Amit1979-UniBonn** [comment]
Dear Adrian,
how are you doing?

I was thinking that your point of view reading Lambda coefficient is right
however, if we want to compare two dataset from different source, it would
be nice to modify the current implementation. In any case modifying the
equation will make metrica more robust.
what do you think?

Best Regards,
Amit

**Comment by adriancorrendo** [comment]
Hi, Amit,

No, the metrica equation will remain the same as it is not affected by the k term, because for the predicted observed case, k is equal to 0. Note also that lamba, on this case is equal to CCC. If k is different from 0 lambda should not be used.

That would be important for other cases beyond the scope of metrica but not for predicted vs observed.

Best,

Adrian
